eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8881/eureka/
server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xiBei-luo/JAVA
          search-paths: springCloudServer/src/main/resources
  application:
    name: config-server