server:
   port: 8761

eureka:
   instance:
       hostname: localhost
   client:
       registerWithEureka: false #false表示不向注册中心注册自己。
       fetchRegistry: false #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
       serviceUrl:
           defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#spring:
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/xiBei-luo/JAVA
#          search-paths: springCloudServer/src/main/resources
#  application:
#    name: config-server

