server:
  port: 8080
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
  datasource:
    url: jdbc:mysql://localhost:3306/luotest?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: luo820
#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.luo.filetest.model.Bank