spring:
  resources:
    static-locations: classpath:/static/
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    mode: HTML5
    encoding: utf-8
  datasource:
    url: jdbc:mysql://localhost:3306/greenplatform?useSSL=false
    username: appuser
    password: luo820
    driver-class-name: com.mysql.jdbc.Driver
  aop:
    auto: true
  jmx:
    enabled: false
mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  type-aliases-package: com.greenplatform.model
server:
  port: 80
  servlet:
    context-path: /GreenPlatformCMS  #请求上下文
#logging:
#  level:
#    com:
#      greenplatform:
#        dao: debug

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  pageSizeZero: false  #pageSize=0
  params: count=countSql


