spring:
  resources:
    static-locations: classpath:/static/
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    mode: HTML5
    encoding: utf-8
  datasource:
    url: jdbc:mysql://localhost:3306/luotest?useSSL=false
    username: luowenlv
    password: luo820
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.luo.model.AreaModel
server:
  port: 8081

