server:
  port: 8088
mybatis:
  mapper-locations: classpath:mappers/**/*.xml
  type-aliases-package: com.property.model
spring:
  resources:
    static-locations: classpath:/static/
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    mode: HTML5
    encoding: utf-8
  datasource:
    url: jdbc:mysql://localhost:3306/web_common?useSSL=false&serverTimezone=UTC
    username: root
    password: luo820
    driver-class-name: com.mysql.cj.jdbc.Driver
  aop:
    auto: true
  devtools:
    restart:
      enabled: true                      #设置开启热部署
      additional-paths: src/main/java        #重启目录
      exclude: WEB-INF/**

#logging:
#  level:
#    com:
#      plate:
#        publicmag:
#          dao: debug
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  pageSizeZero: false  #pageSize=0
  params: count=countSql